version: "3"
services:
  HubService:
    image: selenium/hub:4.5.0
    container_name: seleniumHub
    ports:
      - "4442-4444:4442-4444" 
    # environment:
    #   - GRID_BROWSER_TIMEOUT=0
    #   - GRID_TIMEOUT=300000
    #   - GRID_MAX_SESSION=6
    #   - GRID_CLEAN_UP_CYCLE=600000
    #   - GRID_UNREGISTER_IF_STILL_DOWN_AFTER=600000

  ChromeService:
    image: selenium/node-chrome:4.5.0
    shm_size: "512mb"
    ports:
      - "5900"  
    environment:
      - SE_EVENT_BUS_HOST=seleniumHub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SE_OPTS=--session-timeout 500000
    depends_on:
      - HubService 
